# Generated by Django 5.0 on 2023-12-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0002_alter_video_file_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='file_path',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
